//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroValuedCreditNotes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long ID { get; set; }
        public Nullable<long> CorrectedSaleID { get; set; }
        public Nullable<int> CreditReasonID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public int DocTypeID { get; set; }
        public System.DateTime DocDate { get; set; }
        public long DocNo { get; set; }
        public decimal VATPercent { get; set; }
        public int MOLID { get; set; }
        public string Remark { get; set; }
        public int AppUserID { get; set; }
        public Nullable<System.DateTime> AppUserTime { get; set; }
        public Nullable<System.DateTime> PaymentConsignDate { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<System.DateTime> RebatePeriodFrom { get; set; }
        public bool isCashRegistered { get; set; }
        public bool isPayed { get; set; }
        public bool isPrinted { get; set; }
        public Nullable<int> ManipulUserID { get; set; }
        public Nullable<System.DateTime> ManipulUserTime { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<System.DateTime> DriverTime { get; set; }
        public Nullable<int> RouteID { get; set; }
        public int PaymentTypeID { get; set; }
        public int PaymentTimeID { get; set; }
        public int DiscountTypeID { get; set; }
        public Nullable<decimal> TotalPriceNoVAT { get; set; }
        public Nullable<decimal> TotalDiscountSum { get; set; }
        public Nullable<decimal> TotalDeliveryPrice { get; set; }
        public Nullable<decimal> PaymentSum { get; set; }
        public decimal RebateSumCorrection { get; set; }
        public decimal PayedRebateSum { get; set; }
        public bool isColumnNaturalRebatePercent { get; set; }
        public bool isSalePriceWithoutDiscount { get; set; }
        public bool isMathDiscountType { get; set; }
        public string SpecialDrugForm { get; set; }
        public bool isCustomerDelayPayments { get; set; }
        public bool isPricing { get; set; }
        public Nullable<decimal> TotalBasePrice { get; set; }
        public Nullable<System.DateTime> PaymentDateValuta { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> TotalAdditionalDiscountSum { get; set; }
        public Nullable<decimal> AdditionalRebateSumCorrection { get; set; }
        public Nullable<decimal> PayedAdditionalRebateSum { get; set; }
        public Nullable<bool> isSalePriceWithoutRounding { get; set; }
        public Nullable<System.DateTime> DistributeTime { get; set; }
        public Nullable<bool> isArchive { get; set; }
        public Nullable<bool> isPharmacyPriceWithoutDiscount { get; set; }
        public Nullable<System.DateTime> OverdueInterestPeriodFrom { get; set; }
        public Nullable<decimal> TotalNetoBasePrice { get; set; }
        public Nullable<decimal> TotalNetoNetoBasePrice { get; set; }
        public Nullable<bool> isJoined { get; set; }
        public Nullable<System.DateTime> OverdueInterestPeriodTo { get; set; }
        public Nullable<int> TargetActionID { get; set; }
        public Nullable<bool> isHighCost { get; set; }
        public Nullable<bool> isFCOrder { get; set; }
        public Nullable<byte> VendorID { get; set; }
        public Nullable<bool> isPositioned { get; set; }
    }
}
